from strategy.MA import strategy_by_MA
from strategy.RSI import strategy_by_RSI
from strategy.MA_RSI import strategy_by_MA_RSI
from strategy.simple_buy_hold import strategy_by_simple_buy_and_hold
from strategy.mean_reversion import strategy_by_mean_reversion
from strategy.simple_lin_reg import strategy_by_simple_lin_reg
from strategy.MACD import strategy_by_MACD
